imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: parameters_platform.php } #for platform.sh

    #- { resource: "@AdminBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    esi: { enabled: true }            
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    #fragments:       ~
    fragments: { path: /_fragment }
    http_method_override: true
    #fragments: { path: /ajax_bag_user }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: 5.6
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs
        uglifycss:
            bin: /usr/local/bin/uglifycss
    assets:
        my_jquery:
            inputs:
                - '@UserBundle/Resources/js/thirdparty/jquery-3.1.1.min.js'
        my_bootstrap:
            inputs:
                - 'assets/vendor/bootstrap/dist/js/bootstrap.min.js'

fos_js_routing:
    routes_to_expose: [ ajax_bag_user, ajax_checkout_user, bag_register, basket_big_change, index_user ]

liip_imagine:
    resolvers:
        default:
            web_path: ~

        profile_photos:
            web_path:
                web_root: "%kernel.root_dir%/../web"
                cache_prefix: "media/cache"

    #cache: profile_photos

    filter_sets:
        cache: ~

        # the name of the "filter set"
        my_thumb_show:
            filters:
                thumbnail: { size: [360, 260], mode: outbound } #[240, 180]
        my_thumb_category:
            filters:
                thumbnail: { size: [360, 260], mode: outbound }
        my_thumb_subcat:
            filters:
                thumbnail: { size: [340, 240], mode: outbound }
        my_thumb_cart:
            filters:
                thumbnail: { size: [60, 50], mode: outbound }