imports:
    - { resource: config.yml }
    #- { resource: config_prod_secrets.php } #for fortrabbit

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#framework:
#    session:
        # set handler_id to null to use default session handler from php.ini (memcached)
#        handler_id:  ~ # for fortrabbit

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream #stream locale #error_log for fortrabbit
            path:  "%kernel.logs_dir%/%kernel.environment%.log" #"%kernel.logs_dir%/%kernel.environment%.log" locale #'php://stderr' for heroku
            level: debug
        console:
            type:  console
