app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /myapp

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    # prefix:   /user

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

bag_register_secure:
    path:      /user/bag_register
    #defaults: { _controller: UserBundle:indexUser:bagRegister, requires_channel: http }
    #schemes:  [http]

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

